# Generated by Django 2.1 on 2018-08-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
