# Generated by Django 2.1 on 2018-08-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_music_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('name',), 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
