# Generated by Django 2.1 on 2018-08-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0007_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='band',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='music',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
