# Generated by Django 2.1 on 2018-08-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0009_auto_20180807_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={},
        ),
    ]
