# Generated by Django 2.1 on 2018-08-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0010_auto_20180807_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='playlist.Genre'),
        ),
        migrations.AlterField(
            model_name='band',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_bands', to='playlist.Record'),
        ),
    ]
