# Generated by Django 2.1 on 2018-08-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0011_auto_20180807_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.AlterField(
            model_name='music',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_musics', to='playlist.Band'),
        ),
        migrations.AlterField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='playlist.Playlist'),
        ),
    ]
