# Generated by Django 2.0.6 on 2018-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0012_auto_20180807_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
