# Generated by Django 2.0.6 on 2018-08-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0013_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='playlist.Usuario'),
            preserve_default=False,
        ),
    ]
